"""添加评估报告字段

Revision ID: 1c0cdf27f7d7
Revises: af98a62d2f74
Create Date: 2026-01-05 17:39:24.544920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0cdf27f7d7'
down_revision = 'af98a62d2f74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('evaluation_report', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('evaluation_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'evaluation_generated_at')
    op.drop_column('interviews', 'evaluation_report')
    # ### end Alembic commands ###