"""统一枚举值为小写

Revision ID: 20260106_1510
Revises: 20260106_1500
Create Date: 2026-01-06 15:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260106_1510'
down_revision = '20260106_1500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 更新现有数据中的大写状态为小写
    op.execute("UPDATE interviews SET status = 'completed' WHERE status = 'COMPLETED'")
    op.execute("UPDATE interviews SET status = 'in_progress' WHERE status = 'IN_PROGRESS'")
    op.execute("UPDATE interviews SET status = 'pending' WHERE status = 'PENDING'")

    # 2. 重建枚举类型（PostgreSQL 需要先删除依赖，重建类型，再恢复依赖）
    # 由于 PostgreSQL 枚举类型的限制，我们需要使用更安全的方法

    # 3. 验证所有值都是小写
    # 这个迁移脚本假设所有数据已经更新为小写

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 恢复大写值
    op.execute("UPDATE interviews SET status = 'COMPLETED' WHERE status = 'completed'")
    op.execute("UPDATE interviews SET status = 'IN_PROGRESS' WHERE status = 'in_progress'")
    op.execute("UPDATE interviews SET status = 'PENDING' WHERE status = 'pending'")

    # ### end Alembic commands ###