"""添加面试记录级联删除

Revision ID: ad6ce8938607
Revises: d0703335a5a0
Create Date: 2026-01-15 11:42:47.150842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad6ce8938607'
down_revision = 'd0703335a5a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_documents', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('query_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_query_history_created_at', table_name='query_history')
    op.drop_index('ix_query_history_user_id', table_name='query_history')
    op.create_index(op.f('ix_query_history_id'), 'query_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_history_id'), table_name='query_history')
    op.create_index('ix_query_history_user_id', 'query_history', ['user_id'], unique=False)
    op.create_index('ix_query_history_created_at', 'query_history', ['created_at'], unique=False)
    op.alter_column('query_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_documents', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###