"""添加简历原始文本字段

Revision ID: f05a0073050f
Revises: ab3198cbc0b8
Create Date: 2026-01-20 09:48:57.237936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05a0073050f'
down_revision = 'ab3198cbc0b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interviews_resume_id_fkey', 'interviews', type_='foreignkey')
    op.create_foreign_key(None, 'interviews', 'resumes', ['resume_id'], ['id'])
    op.add_column('resumes', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'raw_text')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_foreign_key('interviews_resume_id_fkey', 'interviews', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###