"""修复面试记录级联删除配置

Revision ID: ab3198cbc0b8
Revises: ad6ce8938607
Create Date: 2026-01-15 11:43:46.864953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3198cbc0b8'
down_revision = 'ad6ce8938607'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除旧的外键约束
    op.execute("""
        ALTER TABLE interviews
        DROP CONSTRAINT IF EXISTS interviews_resume_id_fkey
    """)

    # 添加新的外键约束,带 ON DELETE CASCADE
    op.execute("""
        ALTER TABLE interviews
        ADD CONSTRAINT interviews_resume_id_fkey
        FOREIGN KEY (resume_id) REFERENCES resumes(id)
        ON DELETE CASCADE
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 恢复原来的外键约束
    op.execute("""
        ALTER TABLE interviews
        DROP CONSTRAINT IF EXISTS interviews_resume_id_fkey
    """)

    op.execute("""
        ALTER TABLE interviews
        ADD CONSTRAINT interviews_resume_id_fkey
        FOREIGN KEY (resume_id) REFERENCES resumes(id)
    """)
    # ### end Alembic commands ###