"""添加知识库分段策略支持

Revision ID: f4a2251a6dd5
Revises: 18cfa60f887c
Create Date: 2026-01-21 17:22:34.200551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4a2251a6dd5'
down_revision = '18cfa60f887c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 chunk_strategy 字段到 knowledge_documents 表
    op.add_column('knowledge_documents', sa.Column('chunk_strategy', sa.String(length=50), nullable=True, server_default='semantic'))
    # 添加 parent_chunk_id 字段到 vector_chunks 表
    op.add_column('vector_chunks', sa.Column('parent_chunk_id', sa.Integer(), nullable=True))
    # 创建外键约束
    op.create_foreign_key('fk_vector_chunks_parent_chunk', 'vector_chunks', 'vector_chunks', ['parent_chunk_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除外键约束
    op.drop_constraint('fk_vector_chunks_parent_chunk', 'vector_chunks', type_='foreignkey')
    # 删除 parent_chunk_id 字段
    op.drop_column('vector_chunks', 'parent_chunk_id')
    # 删除 chunk_strategy 字段
    op.drop_column('knowledge_documents', 'chunk_strategy')
    # ### end Alembic commands ###