"""添加问题生成状态和错误字段

Revision ID: 20260106_1500
Revises: e731651bcda8
Create Date: 2026-01-06 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260106_1500'
down_revision = 'e731651bcda8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 添加 generation_error 字段
    op.add_column('interviews', sa.Column('generation_error', sa.Text(), nullable=True))

    # 修改 status 列的枚举类型，添加 'initializing' 选项
    # PostgreSQL 需要先创建新类型，然后修改列类型
    op.execute("ALTER TYPE interviewstatus ADD VALUE 'initializing'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除 generation_error 字段
    op.drop_column('interviews', 'generation_error')

    # 注意：PostgreSQL 不支持直接删除枚举值，需要重建类型
    # 这里简化处理，实际生产环境可能需要更复杂的降级逻辑

    # ### end Alembic commands ###